name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Puedes poner 'latest' si lo prefieres

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --base-href=/CCS.git/

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx angular-cli-ghpages --dir=dist/CCS
